<?php if($this->displayNameChanged){
	echo $this->alert('display_name_has_been_changed','alert-success',false);
?>
<script type="text/javascript">
	if('undefined' != typeof oController)oController.setUserDisplayName(<?=$this->escapeJson($this->authenticatedUser->getUserDisplayName())?>);
</script>
<button class="btn btn-small btn-primary pull-right" type="button" data-dismiss=".modal"><?=$this->translate('close_modal')?></button>
<?php }
else{
	echo $this->form($this->form,\TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL,true);
?>
<script type="text/javascript">
	if(document.id){
		var oUserDisplayName = document.id('new_user_display_name');
		if(oUserDisplayName)oUserDisplayName.focus();
	}
</script>
<?php } ?>