language: php

php:
 - "5.4"

before_install:
 - composer self-update
 - composer install --dev -o

before_script:
 - mysql -e 'create database `app-user-tests`;'
 - cd tests

script:
 - phpunit
 - php ./coverage-checker.php ./clover.xml 100