<?php
return array(
    'BoilerAppUser\Module'                                         => __DIR__ . '/Module.php',
    'BoilerAppUser\Controller\UserAccountController'               => __DIR__ . '/src/BoilerAppUser/Controller/UserAccountController.php',
    'BoilerAppUser\Controller\UserController'                      => __DIR__ . '/src/BoilerAppUser/Controller/UserController.php',
    'BoilerAppUser\Entity\UserEntity'                              => __DIR__ . '/src/BoilerAppUser/Entity/UserEntity.php',
    'BoilerAppUser\Factory\ChangeAvatarFormFactory'                => __DIR__ . '/src/BoilerAppUser/Factory/ChangeAvatarFormFactory.php',
    'BoilerAppUser\Factory\ChangeEmailFormFactory'                 => __DIR__ . '/src/BoilerAppUser/Factory/ChangeEmailFormFactory.php',
    'BoilerAppUser\Factory\ChangePasswordFormFactory'              => __DIR__ . '/src/BoilerAppUser/Factory/ChangePasswordFormFactory.php',
    'BoilerAppUser\Factory\UserAccountServiceFactory'              => __DIR__ . '/src/BoilerAppUser/Factory/UserAccountServiceFactory.php',
    'BoilerAppUser\Factory\UserModelFactory'                       => __DIR__ . '/src/BoilerAppUser/Factory/UserModelFactory.php',
    'BoilerAppUser\Factory\UserServiceFactory'                     => __DIR__ . '/src/BoilerAppUser/Factory/UserServiceFactory.php',
    'BoilerAppUser\Form\ChangeAvatarForm'                          => __DIR__ . '/src/BoilerAppUser/Form/ChangeAvatarForm.php',
    'BoilerAppUser\Form\ChangeEmailForm'                           => __DIR__ . '/src/BoilerAppUser/Form/ChangeEmailForm.php',
    'BoilerAppUser\Form\ResetPasswordForm'                         => __DIR__ . '/src/BoilerAppUser/Form/ResetPasswordForm.php',
    'BoilerAppUser\Model\UserModel'                                => __DIR__ . '/src/BoilerAppUser/Model/UserModel.php',
    'BoilerAppUser\Model\UserProviderModel'                        => __DIR__ . '/src/BoilerAppUser/Model/UserProviderModel.php',
    'BoilerAppUser\Mvc\Controller\Plugin\UserMustBeLoggedInPlugin' => __DIR__ . '/src/BoilerAppUser/Mvc/Controller/Plugin/UserMustBeLoggedInPlugin.php',
    'BoilerAppUser\Repository\UserRepository'                      => __DIR__ . '/src/BoilerAppUser/Repository/UserRepository.php',
    'BoilerAppUser\Service\UserAccountService'                     => __DIR__ . '/src/BoilerAppUser/Service/UserAccountService.php',
    'BoilerAppUser\Service\UserService'                            => __DIR__ . '/src/BoilerAppUser/Service/UserService.php',
    'BoilerAppUser\Validator\UserLoggedPasswordValidator'          => __DIR__ . '/src/BoilerAppUser/Validator/UserLoggedPasswordValidator.php',
    'BoilerAppUser\View\Helper\UserAvatarHelper'                   => __DIR__ . '/src/BoilerAppUser/View/Helper/UserAvatarHelper.php',
);