<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'BoilerAppUser\Controller\UserAccountController'             => __DIR__ . '/src/BoilerAppUser/Controller/UserAccountController.php',
    'BoilerAppUser\Entity\UserEntity'                            => __DIR__ . '/src/BoilerAppUser/Entity/UserEntity.php',
    'BoilerAppUser\Factory\ChangeUserAvatarFormFactory'          => __DIR__ . '/src/BoilerAppUser/Factory/ChangeUserAvatarFormFactory.php',
    'BoilerAppUser\Factory\ChangeUserDisplayNameFormFactory'     => __DIR__ . '/src/BoilerAppUser/Factory/ChangeUserDisplayNameFormFactory.php',
    'BoilerAppUser\Factory\UserAccountServiceFactory'            => __DIR__ . '/src/BoilerAppUser/Factory/UserAccountServiceFactory.php',
    'BoilerAppUser\Factory\UserAvatarHelperFactory'              => __DIR__ . '/src/BoilerAppUser/Factory/UserAvatarHelperFactory.php',
    'BoilerAppUser\Factory\UserServiceFactory'                   => __DIR__ . '/src/BoilerAppUser/Factory/UserServiceFactory.php',
    'BoilerAppUser\Form\ChangeUserAvatarForm'                    => __DIR__ . '/src/BoilerAppUser/Form/ChangeUserAvatarForm.php',
    'BoilerAppUser\Form\ChangeUserDisplayNameForm'               => __DIR__ . '/src/BoilerAppUser/Form/ChangeUserDisplayNameForm.php',
    'BoilerAppUser\InputFilter\ChangeUserAvatarInputFilter'      => __DIR__ . '/src/BoilerAppUser/InputFilter/ChangeUserAvatarInputFilter.php',
    'BoilerAppUser\InputFilter\ChangeUserDisplayNameInputFilter' => __DIR__ . '/src/BoilerAppUser/InputFilter/ChangeUserDisplayNameInputFilter.php',
    'BoilerAppUser\Repository\UserRepository'                    => __DIR__ . '/src/BoilerAppUser/Repository/UserRepository.php',
    'BoilerAppUser\Service\UserAccountService'                   => __DIR__ . '/src/BoilerAppUser/Service/UserAccountService.php',
    'BoilerAppUser\Service\UserService'                          => __DIR__ . '/src/BoilerAppUser/Service/UserService.php',
    'BoilerAppUser\Validator\DisplayNameAvailabilityValidator'   => __DIR__ . '/src/BoilerAppUser/Validator/DisplayNameAvailabilityValidator.php',
    'BoilerAppUser\View\Helper\UserAvatarHelper'                 => __DIR__ . '/src/BoilerAppUser/View/Helper/UserAvatarHelper.php',
);
